# 基础知识

## 1 NDarray

In [3]:
from mxnet import nd

In [25]:
# 创建NDarray
x = nd.arange(12)
print(x.shape,x.size,x)

(12,) 12 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


In [26]:
x = x.reshape((3,4))
print(x)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


In [27]:
nd.zeros((2,3,4))
#nd.ones((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [39]:
y = nd.array([[1,2,3,4],[5,6,7,6],[1,2,3,4]])
print(y)


[[1. 2. 3. 4.]
 [5. 6. 7. 6.]
 [1. 2. 3. 4.]]
<NDArray 3x4 @cpu(0)>


In [40]:
nd.random.normal(0, 1, shape=(3, 4))


[[-1.8815191  -0.7205708  -0.3560157  -0.15963984]
 [ 1.7974477   0.19594945 -1.7376398   0.04734707]
 [ 0.14580931  0.32604915  0.4578783  -0.89425814]]
<NDArray 3x4 @cpu(0)>

### 运算

In [43]:
print(x+y, x*y, x/y)


[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 13.]
 [ 9. 11. 13. 15.]]
<NDArray 3x4 @cpu(0)> 
[[ 0.  2.  6. 12.]
 [20. 30. 42. 42.]
 [ 8. 18. 30. 44.]]
<NDArray 3x4 @cpu(0)> 
[[0.         0.5        0.6666667  0.75      ]
 [0.8        0.8333333  0.85714287 1.1666666 ]
 [8.         4.5        3.3333333  2.75      ]]
<NDArray 3x4 @cpu(0)>


In [46]:
print(x.exp(), nd.exp(y), nd.dot(x, y.T))


[[1.0000000e+00 2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342880e+02 1.0966332e+03]
 [2.9809580e+03 8.1030840e+03 2.2026465e+04 5.9874141e+04]]
<NDArray 3x4 @cpu(0)> 
[[   2.7182817    7.389056    20.085537    54.59815  ]
 [ 148.41316    403.4288    1096.6332     403.4288   ]
 [   2.7182817    7.389056    20.085537    54.59815  ]]
<NDArray 3x4 @cpu(0)> 
[[ 20.  38.  20.]
 [ 60. 134.  60.]
 [100. 230. 100.]]
<NDArray 3x3 @cpu(0)>


In [47]:
# 使用nd.concat连接两个矩阵，dim指定连接的轴，也就是shape中第几个位置的轴会相加
print(nd.concat(x, y, dim=0), nd.concat(x, y, dim=1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 1.  2.  3.  4.]
 [ 5.  6.  7.  6.]
 [ 1.  2.  3.  4.]]
<NDArray 6x4 @cpu(0)> 
[[ 0.  1.  2.  3.  1.  2.  3.  4.]
 [ 4.  5.  6.  7.  5.  6.  7.  6.]
 [ 8.  9. 10. 11.  1.  2.  3.  4.]]
<NDArray 3x8 @cpu(0)>


In [48]:
print(x==y)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>


In [53]:
# asscalar()将矩阵变为标量
print(x.norm().asscalar(),x.sum())

22.494442 
[66.]
<NDArray 1 @cpu(0)>


### 广播

In [55]:
A = nd.arange(3).reshape((3,-1))
B = nd.arange(2).reshape((-1,2))
print(B,A)


[[0. 1.]]
<NDArray 1x2 @cpu(0)> 
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>


In [56]:
print(A+B, A*B)


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)> 
[[0. 0.]
 [0. 1.]
 [0. 2.]]
<NDArray 3x2 @cpu(0)>


### 索引

In [60]:
print(x[0:2], x[:, 0:2])


[[0. 1. 9. 3.]
 [4. 5. 6. 7.]]
<NDArray 2x4 @cpu(0)> 
[[0. 1.]
 [4. 5.]
 [8. 9.]]
<NDArray 3x2 @cpu(0)>


In [58]:
x[0, 2] = 9
print(x)


[[ 0.  1.  9.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


### 运算内存开销

In [62]:
before = id(y)
y = x + y 
print(id(y) == before)

False


In [66]:
z = nd.zeros_like(y)
before = id(z)
z[:] = x + y
print(id(z) == before) 

True


In [68]:
#使用运算符全名函数
nd.elemwise_add(x, y, out=z)
print(id(z) == before) 
#以下均可节约内存
# x[:] = x + y
# x += y

True


## 与NumPy互转

In [71]:
import numpy as np
p = np.array([1,2,3])
print(p)
dp = nd.array(p)
print(dp)
dp.asnumpy()

[1 2 3]

[1. 2. 3.]
<NDArray 3 @cpu(0)>


array([1., 2., 3.], dtype=float32)

## 2 autograd

In [72]:
from mxnet import autograd, nd

In [77]:
x = nd.arange(4).reshape((4,1))
print(x)


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>


In [78]:
x.attach_grad()
with autograd.record():
    y = 2 * nd.dot(x.T, x)

y.backward()

In [79]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [82]:
assert(x.grad - 4*x).norm().asscalar()==0

### 训练模式和预测模式

In [85]:
print(autograd.is_training())
# 在使用recode()函数后会进入训练模式，记录梯度
with autograd.record():
    print(autograd.is_training())

False
True


### python控制流下的自动求导

In [88]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [89]:
a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

### 非标量变量的backward

In [108]:
aa = nd.array([[3,4],[1,2]])

In [ ]:
aa.attach_grad()
with autograd.rconrd():
    c = 